version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5.0
    working_directory: ~/repo
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-
      - run: yarn install
      # - save_cache:
          # root: ~/repo
          # paths:
          #   - node_modules
          # key: key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: test
          command: yarn test
